//! Every tunable in one place, loadable from `scry.toml`.
//!
//! Precedence: built-in defaults < `scry.toml` at the scanned root < `--config <file>`
//! < explicit CLI flags. Every section and every key is optional, so a repo's
//! file only has to name what it changes. `scry config <root>` prints the
//! effective result as TOML, which is the easiest starting point for a new file.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

/// File name looked for at the scanned root.
pub const FILE_NAME: &str = "scry.toml";

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Config {
    pub discover: Discover,
    pub history: History,
    pub metrics: Metrics,
    pub deps: Deps,
    pub clones: Clones,
    pub report: Report,
    pub tests: Tests,
    pub plan: Plan,
}

impl Config {
    /// Defaults, then the root's `scry.toml` if present, then `explicit` if given.
    pub fn load(root: &Path, explicit: Option<&Path>) -> Result<Self> {
        let mut cfg = Config::default();
        let at_root = root.join(FILE_NAME);
        if at_root.is_file() {
            cfg = Self::parse_into(cfg, &at_root)?;
        }
        if let Some(p) = explicit {
            cfg = Self::parse_into(cfg, p)?;
        }
        Ok(cfg)
    }

    /// A file's contents override `base` field by field; sections it omits keep `base`.
    fn parse_into(base: Self, path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        // Layering: serialize the base, splice the file's tables over it, deserialize.
        let mut merged: toml::Table = toml::Table::try_from(&base).context("serializing defaults")?;
        let over: toml::Table = toml::from_str(&text).with_context(|| format!("parsing {}", path.display()))?;
        merge_tables(&mut merged, over);
        merged.try_into().with_context(|| format!("invalid {}", path.display()))
    }

    pub fn to_toml(&self) -> String {
        toml::to_string_pretty(self).expect("config serializes")
    }
}

fn merge_tables(base: &mut toml::Table, over: toml::Table) {
    for (k, v) in over {
        match (base.get_mut(&k), v) {
            (Some(toml::Value::Table(b)), toml::Value::Table(o)) => merge_tables(b, o),
            (_, v) => {
                base.insert(k, v);
            }
        }
    }
}

fn strings(v: &[&str]) -> Vec<String> {
    v.iter().map(|s| s.to_string()).collect()
}

// ---------- discover ----------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Discover {
    /// Gitignore-style globs dropped from the walk entirely (`art/**`, `scripts/*.py`).
    pub exclude: Vec<String>,
    /// Any path component in this list marks the file Vendored.
    pub vendor_dirs: Vec<String>,
    /// Any path component in this list marks the file Test.
    pub test_dirs: Vec<String>,
    /// Any path component in this list marks the file Data.
    pub data_dirs: Vec<String>,
    /// Any path component in this list marks the file Generated.
    pub generated_dirs: Vec<String>,
    /// File-stem prefixes that mark a Test file (`test_x.py`).
    pub test_stem_prefixes: Vec<String>,
    /// File-stem suffixes that mark a Test file (`x_test.go`, `x.spec.ts`).
    pub test_stem_suffixes: Vec<String>,
    /// Exact stems that are Test files.
    pub test_stems: Vec<String>,
    /// Stem substrings that mark a Data file.
    pub data_stem_contains: Vec<String>,
    /// Lower-cased phrases in the first `generated_marker_lines` lines that mark Generated.
    pub generated_markers: Vec<String>,
    pub generated_marker_lines: usize,
    /// A file this long or longer with a control-flow line share below
    /// `data_max_logic_density` is Data, not Source.
    pub data_min_lines: usize,
    pub data_max_logic_density: f64,
}

impl Default for Discover {
    fn default() -> Self {
        Self {
            exclude: vec![],
            vendor_dirs: strings(&[
                "node_modules", "vendor", "third_party", "thirdparty", "dist", "build", "target",
                ".venv", "venv", "site-packages", "__pycache__", ".git",
            ]),
            test_dirs: strings(&["test", "tests", "__tests__", "e2e", "spec", "specs", "testing"]),
            data_dirs: strings(&["fixtures", "fixture", "snapshots", "__snapshots__", "testdata"]),
            generated_dirs: strings(&["migrations", "generated", "__generated__", "gen"]),
            test_stem_prefixes: strings(&["test_"]),
            test_stem_suffixes: strings(&["_test", ".test", ".spec", ".snapshots", "Probes"]),
            test_stems: strings(&["conftest"]),
            data_stem_contains: strings(&["fixture"]),
            generated_markers: strings(&[
                "@generated", "do not edit", "auto-generated", "automatically generated", "generated by",
            ]),
            generated_marker_lines: 8,
            data_min_lines: 150,
            data_max_logic_density: 0.04,
        }
    }
}

// ---------- history ----------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct History {
    /// `git log --since` window.
    pub since: String,
    /// Whole words that make a commit subject a fix.
    pub fix_words: Vec<String>,
    /// Commits touching more files than this are mass edits: no co-change evidence, and (when
    /// `fix_mass_edit_cap`) no fix evidence either. Judged on everything the commit touched.
    pub max_cochange_commit_size: usize,
    /// A fix word on a commit over `max_cochange_commit_size` does not make it a fix commit for
    /// the files it touched (a 49-file "review pass: fix eleven defects" says nothing about which
    /// file was broken); it still counts as a commit.
    pub fix_mass_edit_cap: bool,
    /// Case-insensitive substrings of an author name that mark a bot. Bot commits still count as
    /// commits but never toward a file's author set, so the bus-factor reason ignores them.
    pub bot_patterns: Vec<String>,
    /// A co-change pair needs at least this many shared commits…
    pub min_cochange_together: usize,
    /// …and together / min(commits_a, commits_b) at least this. Both are judged on non-sweep counts.
    pub min_cochange_strength: f64,
    /// A commit is a directory sweep when, for some directory holding at least
    /// `sweep_min_dir_files` tracked Source files, it touches at least this share of them…
    pub sweep_fraction: f64,
    /// …in a directory holding at least this many tracked Source files (smaller directories can
    /// never qualify a sweep)…
    pub sweep_min_dir_files: usize,
    /// …and at least this many of them (a 2-file fix in a 4-file directory is not a sweep).
    /// Sweeps still count as churn (commits, fix commits, authors) but never toward pair counts.
    pub sweep_min_files: usize,
    /// Pairs with lift below this are dropped, where lift = together_nonsweep / (commits_a x
    /// commits_b / N) with the per-file commit counts (sweeps included) and N = non-sweep commits…
    pub min_lift: f64,
    /// …but only once N is at least this; below it lift is reported and not applied.
    pub min_commits_for_lift: usize,
    /// A pair whose members both import a file that changed in at least this share of their
    /// co-commits is `explained_by` that import: shotgun surgery on it, not hidden coupling.
    pub explained_min_share: f64,
}

impl Default for History {
    fn default() -> Self {
        Self {
            since: "6 months ago".into(),
            fix_words: strings(&[
                "fix", "fixes", "fixed", "fixing", "bugfix", "bugfixes", "hotfix", "hotfixes",
                "bug", "bugs", "buggy", "regression", "regressions", "regress", "regressed",
                "broke", "broken", "crash", "crashes", "crashed", "crashing",
                "repair", "repairs", "repaired", "correct", "corrects", "corrected", "correction",
                "patch", "patched", "wrong", "incorrect", "flake", "flaky", "flakey",
            ]),
            max_cochange_commit_size: 25,
            fix_mass_edit_cap: true,
            bot_patterns: strings(&["[bot]", "dependabot", "renovate", "pre-commit-ci"]),
            min_cochange_together: 3,
            min_cochange_strength: 0.4,
            sweep_fraction: 0.5,
            sweep_min_dir_files: 4,
            sweep_min_files: 6,
            min_lift: 3.0,
            min_commits_for_lift: 20,
            explained_min_share: 0.5,
        }
    }
}

// ---------- metrics ----------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Metrics {
    /// Functions above this cognitive complexity are "hard to follow".
    pub cognitive_hard: u32,
}

impl Default for Metrics {
    fn default() -> Self {
        Self { cognitive_hard: 15 }
    }
}

// ---------- deps ----------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Deps {
    /// JS/TS import-prefix aliases: `"@/" = "src"` maps `@/x` to `<nearest src>/x`.
    /// The target is looked for under every ancestor of the importing file.
    pub js_aliases: BTreeMap<String, String>,
    /// A file cycle with at least this many members gets a cut suggestion; smaller ones only
    /// the deduped count line.
    pub min_cycle_size_to_cut: usize,
    /// Internal edges tried for the single-edge cut, cheapest first (an SCC of 15 files has ~70).
    pub max_edges_tried: usize,
    /// The greedy cut set is reported only when it dissolves the cycle within this many edges.
    pub max_cut_set: usize,
    /// Symbol cost of a wildcard import (`use x::*`, `from x import *`, `import * as ns`):
    /// what it pulls in is unknown, so it is never the cheap cut.
    pub glob_import_symbol_cost: u32,
    /// Also try dropping every non-`mod` import of one member (the hub cut); reported when it
    /// leaves a smaller cycle than the best single edge.
    pub report_hub_cut: bool,
    /// Print the cycle once under CYCLES and `in the 15-file src cycle (cut: a -> b, Sym)` on
    /// members, instead of `in an import cycle of 15 files` on every member.
    pub dedupe_cycle_reason: bool,
    /// Compute cuts for Rust cycles. Off keeps the deduped count line but no cut text: the
    /// idiomatic-Rust argument belongs in `[report].cycle_coupling`, not in hiding the cut.
    pub cut_rust_cycles: bool,
    /// TS `import type` / `import { type X }` edges are erased at runtime: leave them out of
    /// the cycle the cuts are searched on.
    pub ignore_type_only_imports: bool,
    /// `no single import breaks this cycle` is appended when the best single cut still leaves
    /// a cycle of at least this share of the members.
    pub no_single_cut_share: f64,
}

impl Default for Deps {
    fn default() -> Self {
        Self {
            js_aliases: [("@/".to_string(), "src".to_string()), ("~/".to_string(), "src".to_string())].into(),
            min_cycle_size_to_cut: 4,
            max_edges_tried: 400,
            max_cut_set: 6,
            glob_import_symbol_cost: 20,
            report_hub_cut: true,
            dedupe_cycle_reason: true,
            cut_rust_cycles: true,
            ignore_type_only_imports: true,
            no_single_cut_share: 0.8,
        }
    }
}

// ---------- clones ----------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Clones {
    /// Tokens per fingerprint window.
    pub k: usize,
    /// Winnowing window: one fingerprint kept per `w` consecutive k-grams.
    pub w: usize,
    /// Shortest run worth reporting, in tokens.
    pub min_tokens: usize,
    /// A fingerprint in more files than this is boilerplate.
    pub max_files: usize,
    /// Hard cap on positions per fingerprint.
    pub max_locations: usize,
    /// Drop a same-file run whose two ranges sit in one container (or nested ones) whose
    /// entries across both ranges are a uniform table: the first half of a `match`, array or
    /// map matching its second half. Sibling items that merely copy each other are kept.
    pub drop_same_container_self_match: bool,
    /// A run's range resolves to the smallest node spanning it, then down into a child spanning
    /// at least this share of its bytes: a run that spills a few tokens past its own item still
    /// resolves to that item, while the two halves of one container resolve to the container.
    /// The same share is what a table's entries must span of the run they are tagged on.
    pub dominant_child_share: f64,
    /// A run side is a table when its container has at least this many consecutive same-kind
    /// named children spanning at least `dominant_child_share` of the run (six imports at the
    /// top of a copied file are under the run, not the run)…
    pub table_min_entries: usize,
    /// …the dominant entry shape (names, paths and literals collapsed) covers at least this
    /// share of them…
    pub table_min_dominant_shape: f64,
    /// …no entry has more named nodes than this (a loose safety cap)…
    pub table_max_entry_nodes: usize,
    /// …and no entry contains one of these node kinds, per grammar (`rust`, `typescript`,
    /// `python`). Rust `try_expression` (`?`) must not be listed: it is in every dispatch arm.
    pub table_control_kinds: BTreeMap<String, Vec<String>>,
    /// Weight of table clone lines in `clone_ratio`: `(logic + table_weight x table) / lines`.
    /// 1.0 ranks parallel maps that must drift together; 0.25 dampens them.
    pub table_weight: f64,
    /// Print table pairs under a TABLES sub-heading of CLONES instead of inline.
    pub list_tables_separately: bool,
}

impl Default for Clones {
    fn default() -> Self {
        Self {
            k: 30,
            w: 20,
            min_tokens: 70,
            max_files: 40,
            max_locations: 2000,
            drop_same_container_self_match: true,
            dominant_child_share: 0.9,
            table_min_entries: 6,
            table_min_dominant_shape: 0.6,
            table_max_entry_nodes: 40,
            table_control_kinds: [
                ("rust", strings(&["if_expression", "match_expression", "for_expression", "while_expression", "loop_expression", "closure_expression"])),
                ("typescript", strings(&["if_statement", "switch_statement", "for_statement", "for_in_statement", "while_statement", "do_statement", "try_statement", "ternary_expression", "arrow_function", "function_expression"])),
                ("python", strings(&["if_statement", "for_statement", "while_statement", "try_statement", "match_statement", "with_statement", "conditional_expression", "lambda", "list_comprehension", "dictionary_comprehension", "set_comprehension", "generator_expression"])),
            ]
            .into_iter()
            .map(|(k, v)| (k.to_string(), v))
            .collect(),
            table_weight: 1.0,
            list_tables_separately: true,
        }
    }
}

// ---------- tests ----------

/// Inline test regions (`#[cfg(test)] mod`, `#[cfg(test)]` items, bare `#[test]` fns) in Rust
/// Source files, and the test-mention index that replaces "a test file imports it".
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Tests {
    /// Apply inline test regions: metrics units inside one are tagged `in_test` and left out of
    /// file totals, `inline_test_lines` come off the size signal, and the clone tokenizer skips
    /// their bytes. Off means every line is source; regions are still detected and listed, and
    /// the mention index finds them on its own tree, so `count_inline_tests_as_refs` is
    /// unaffected.
    pub inline_modules: bool,
    /// A hotspot whose inline test lines / file lines is at or above this gets
    /// `N in #[cfg(test)] mod at a-b` after its line count.
    pub report_inline_ratio_above: f64,
    /// A Source file whose inline test ratio is above this is treated as a Test file for
    /// ranking: it is not a hotspot and does not count toward source lines.
    pub reclassify_file_above_ratio: f64,
    /// Functions inside inline test regions are test units: one that names a symbol of any
    /// Source file counts toward that file's `test_units`. Off, only Test files hold test units.
    pub count_inline_tests_as_refs: bool,
    /// Symbols with names shorter than this are never matched (`run`, `new`, `get`, `parse`
    /// collide with every test); 4 still lets `execute`-length names through, 5 does not
    /// let `commit`/`is_empty`-length generic names collide.
    pub min_name_len: usize,
    /// A file whose share of public symbols named by no test unit is at or above this gets
    /// `N of M public symbols are named by no test: a (lines 1-9), …`…
    pub unmentioned_share_reason: f64,
    /// …when it has at least this many public symbols (a two-symbol file has no share worth a line).
    pub unmentioned_min_symbols: usize,
}

impl Default for Tests {
    fn default() -> Self {
        Self {
            inline_modules: true,
            report_inline_ratio_above: 0.5,
            reclassify_file_above_ratio: 0.9,
            count_inline_tests_as_refs: true,
            min_name_len: 5,
            unmentioned_share_reason: 0.5,
            unmentioned_min_symbols: 3,
        }
    }
}

// ---------- plan ----------

/// What names a clone run that no metrics unit contains.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SymbolFallback {
    /// The nearest preceding top-level named item (a `struct`, `impl`, `static`, a TS
    /// `const`, a Python assignment): the run sits in or after it.
    PrecedingItem,
    /// Print `?`.
    None,
}

/// The per-hotspot refactor plan: clone runs resolved to symbols, one step per finding the
/// other passes already made (a clone pair, a unit over `cognitive_hard`, a cycle cut).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Plan {
    /// Steps printed per hotspot; the rest are counted as `(+N more)`.
    pub max_steps: usize,
    /// Clone runs inside an inline test region (or a Test-classified file) become one
    /// `fold_test_clones` step per file naming the region and the run count. Off, they are
    /// silently left out; either way they never become `canonicalise_clone` steps.
    pub fold_test_clones: bool,
    /// A clone run's `symbol` is the innermost metrics unit containing its start line; when
    /// none does, `preceding_item` names the nearest preceding top-level item and `none`
    /// prints `?`.
    pub symbol_fallback: SymbolFallback,
    /// Step kinds in print order. A kind left out of the list is not planned.
    pub kind_priority: Vec<String>,
    /// Print the `PLAN` block under each hotspot in the text report; `--json` and `scry plan`
    /// carry the steps either way.
    pub include_in_text_report: bool,
}

impl Default for Plan {
    fn default() -> Self {
        Self {
            max_steps: 6,
            fold_test_clones: true,
            symbol_fallback: SymbolFallback::PrecedingItem,
            kind_priority: strings(&["fold_test_clones", "canonicalise_clone", "extract", "cut_cycle_edge"]),
            include_in_text_report: true,
        }
    }
}

// ---------- report ----------

/// Partial `[report.with_history]` tables are filled from the defaults by the
/// table merge in `Config::load`, so every field is required here.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Weights {
    /// sqrt(churn × complexity). Zero without history.
    pub hotspot: f64,
    pub fixes: f64,
    pub complexity: f64,
    pub coupling: f64,
    pub clones: f64,
    pub size: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Report {
    /// Weights when git history joined at least one file.
    pub with_history: Weights,
    /// Weights when it did not (`--no-history`, not a repo, subdirectory scan).
    pub without_history: Weights,
    /// Score multiplier for a file with `test_units == 0`: no test unit names one of its
    /// symbols, no test file imports it, no same-stem test sits in its tree.
    pub no_tests_multiplier: f64,
    /// complexity = this × pct(max cognitive) + (1 − this) × pct(total cognitive).
    pub complexity_max_share: f64,
    /// Coupling floor for a file inside an import cycle.
    pub cycle_coupling: f64,
    /// Reason thresholds.
    pub reason_churn_percentile: f64,
    pub reason_min_fix_commits: usize,
    pub reason_fanin_percentile: f64,
    pub reason_min_fan_in: usize,
    pub reason_clone_ratio: f64,
    pub reason_hidden_partners: usize,
    pub reason_bus_factor_min_commits: usize,
    /// Symbols the `named by no test` reason lists before `+N more`; `unmentioned[]` in `--json`
    /// is never cut.
    pub reason_unmentioned_listed: usize,
}

impl Default for Report {
    fn default() -> Self {
        Self {
            with_history: Weights { hotspot: 0.45, fixes: 0.15, complexity: 0.15, coupling: 0.10, clones: 0.10, size: 0.05 },
            without_history: Weights { hotspot: 0.0, fixes: 0.0, complexity: 0.55, coupling: 0.15, clones: 0.15, size: 0.15 },
            no_tests_multiplier: 1.15,
            complexity_max_share: 0.6,
            cycle_coupling: 0.6,
            reason_churn_percentile: 0.8,
            reason_min_fix_commits: 2,
            reason_fanin_percentile: 0.9,
            reason_min_fan_in: 5,
            reason_clone_ratio: 0.15,
            reason_hidden_partners: 2,
            reason_bus_factor_min_commits: 5,
            reason_unmentioned_listed: 5,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_round_trip_through_toml() {
        let d = Config::default();
        let back: Config = toml::from_str(&d.to_toml()).unwrap();
        assert_eq!(back, d);
    }

    #[test]
    fn partial_file_overrides_only_what_it_names() {
        let dir = std::env::temp_dir().join(format!("scry-cfg-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join(FILE_NAME), "[clones]\nmin_tokens = 50\n\n[report.with_history]\nhotspot = 0.6\n\n[discover]\ntest_dirs = [\"qa\"]\n").unwrap();
        let c = Config::load(&dir, None).unwrap();
        assert_eq!(c.clones.min_tokens, 50);
        assert_eq!(c.clones.k, 30);
        assert_eq!(c.report.with_history.hotspot, 0.6);
        assert_eq!(c.report.with_history.fixes, 0.15);
        assert_eq!(c.discover.test_dirs, vec!["qa"]);
        assert_eq!(c.discover.vendor_dirs, Discover::default().vendor_dirs);
        // An explicit file layers on top of the root file.
        let extra = dir.join("more.toml");
        std::fs::write(&extra, "[clones]\nk = 40\n").unwrap();
        let c2 = Config::load(&dir, Some(&extra)).unwrap();
        assert_eq!((c2.clones.k, c2.clones.min_tokens), (40, 50));
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn unknown_keys_are_errors() {
        let dir = std::env::temp_dir().join(format!("scry-cfg-bad-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join(FILE_NAME), "[clones]\nmin_token = 50\n").unwrap();
        let err = Config::load(&dir, None).unwrap_err();
        assert!(format!("{err:#}").contains("min_token"), "{err:#}");
        std::fs::remove_dir_all(&dir).unwrap();
    }
}
